# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  def root_path
      Dir.pwd.sub(/.*\Kfastlane/, '').sub(/.*\Kandroid/, '').sub(/.*\Kios/, '').sub(/.*\K\/\//, '')
    end

    # Have an easy way to run flutter tasks on the root of the project
    lane :sh_on_root do |options|
      command = options[:command]
      sh("cd #{root_path} && #{command}")
    end

    lane :build_apk do
        sh_on_root(command: "flutter build apk --flavor #{ENV['FLAVOR']} --release --dart-define-from-file=.env/#{ENV['FLAVOR']}.json")
    end

    lane :build_aab do
        sh_on_root(command: "flutter build appbundle --flavor #{ENV['FLAVOR']} --release --dart-define-from-file=.env/#{ENV['FLAVOR']}.json")
    end

    desc "upload to internal track"
    lane :release do
        build_aab
        upload_to_play_store(
#             track: 'internal',
            track: 'alpha',
#             track: 'beta',
#             track: 'production',
            aab: "../build/app/outputs/bundle/productionRelease/app-production-release.aab",
            json_key: ENV["KEY_PATH"],
        )
    end
end
